### PR TITLE
add project week-4

### PR DESCRIPTION
**Pull request by ywyang236**
楊于葳
http://34.211.88.122:3000/
http://34.211.88.122:3000/attraction/11

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We have to call **get current user API** to check user sign-in status. Try to figure out why we should do this.

**Comment by ywyang236** [comment]
To connect @api/user/auth GET with checkUserLoginStatus

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by ywyang236** [comment]
Thank you so much !!!

**Pull request merged**
